void cadastrarReceita(void);
void cadastrarDespesa(void);
void cadastrarPagamento(void);
void incluirProduto(void);
void exibeReceita (Receita* rec);
void gravaReceita (Receita* rec);
void exibePagamento(Pagamento* pag);
void gravaPagamento(Pagamento* pag);
void exibeDespesa (Despesa* des);
void gravaDespesa (Despesa* des);
void exibeProduto (Produto* pro);
void gravaProduto (Produto* pro);
