void cadastrarReceita(void);
void alterarDespesa(void);
void excluirReceita(void);
void cadastrarDespesa(void);
void atualizarDespesa(void);
void excluirDespesa(void);
void cadastrarPagamento(void);
void atualizarPagamento(void);
void excluirPagamento(void);
void alterarProduto(void);
void excluirProduto(void);
void incluirProduto(void);
void consultarOrcamento(void);
void consultarDespesas(void);
void consultarPagamentos(void);

void exibeReceita (void);
void gravaReceita (void);
void exibePagamento(void);
void gravaPagamento(void);
void exibeDespesa (void);
void gravaDespesa (void);
void exibeProduto (void);
void gravaProduto (void);
